### PR TITLE
Add overlap removal and support for electrons

### PR DESCRIPTION
**Pull request by btuan**
Main changes: in `util/runZBJetBalance` the flag `useMuons=true` for muons operation, else, use electron balance algo.

### CODE REVIEW

**Comment by YasuyukiOkumura** [comment]
Dear Brian, 

Thanks for the update for electron part. 

One quick comment. after my quick review, I think that 
the muon in jet correction is not applied in Z->ee analysis case, right? 

If it is the case, 
Please note that muon in b-jet is independent from decay channel of Z, and 
the muon in jet correction should be applied for both analysis case. 

Electron in jet correction is since both of them are observable from calorimeter measurement, 
I image it would be hard to use in short time scale. 

Dear Gabriel & Brian, 

A generic question,
do we want to have separate analysis code between ee and mumu (Root/EEBalanceAlgorithm.cxx)?
It could be duplication of codes, considering apart they should be the identical, apart from Z reconstruction.

Thanks! 

Best regards,
Yasu Okumura

**Comment by btuan** [comment]
Hi Yasu,

  Yes, I misunderstood the purpose of the muon in jet correction -- I will reinstate that through the electron channel. Reviewing the code, I think it should be easy to combine the two analyses into the same balancing algorithm, perhaps by putting a `useMuons`, defaulting as `true` flag in a config file?

  The only thing to remain aware of in this case would be to maintain different event selection parameters for the two cases, i.e. keeping the `useMuons` boolean in the `util/runZBJetBalance.cxx`, since I don't want to enforce tight selections on both 2 electrons and 2 muons on a per-event basis. which would tank the efficiency.

  I'll start merging the two balance algorithms and testing that!

Best,
Brian

**Comment by gfacini** [comment]
Sounds good!

**Comment by YasuyukiOkumura** [comment]
Dear Gabriel and Brian,

Thanks, it sounds good. 

Another concerning : 
I think we forgot to apply "Opposite sign" cut, by looking at charge of leptons. 

Could Gabriel and Brian please confirm or correct it? 

If it is the case, could Brian please add such criteria in the executeAnalysis() 
around https://github.com/UCATLAS/ZJetBalance/blob/master/Root/BalanceAlgorithm.cxx#L353-L360  in your next update?

Best regards,
Yasu Okumura

**Comment by btuan** [comment]
Hi @YasuyukiOkumura,

Just pushed updates to the removal of the two balance algorithms. Just tested it -- seems to work alright! I'll keep testing with various configurations to try to break it :)

Good call! I'm adding that criteria now. Should be up within 10 minutes.

Best,
Brian

**Comment by btuan** [comment]
Hi @YasuyukiOkumura ,

Inelegant, but it should work, no? I'm not sure what the `charge()` returns, since the variable is typed as a `float`, but the charge should be physically quantized to ±1 anyways, right?

```
  if( (signalMuons->at(0)->charge() < 0 && signalMuons->at(1)->charge() < 0) ||
      (signalMuons->at(0)->charge() > 0 && signalMuons->at(1)->charge() > 0) ){
      wk()->skipEvent();  return EL::StatusCode::SUCCESS;
  }
  if(doCutflow) passCut(); // Opposite sign leptons cut.
```

Best,
Brian

**Comment by btuan** [comment]
@YasuyukiOkumura @gfacini ,

All looks good on my end! Final changes pushed and ready to merge.

Best,
Brian

**Comment by gfacini** [comment]
I think this is good! 
@YasuyukiOkumura - are you on board?

**Comment by YasuyukiOkumura** [comment]
Hi all, 

I am reviewing them. I will give you the green light as soon as possible! 

Best regards,
Yasu Okumura

**Comment by gfacini** [comment]
good stuff

**Comment by YasuyukiOkumura** [comment]
Still in checking, 

One comment so far, 
in such line,  
( !m_useMuons && m_inputElectronContainerName.empty() )
in order to avoid the possible ambiguity could you please use
( (!m_useMuons) && m_inputElectronContainerName.empty() )
to be explicit the order of operation. 

Thanks! 

Best regards, 
Yasu Okumura

**Comment by YasuyukiOkumura** [comment]
It looks Ok with me, apart from a minor comment I gave in the last comments.

Thanks a lot for your quick implementation, Brian, 

Best regards,
Yasu Okumura

**Comment by btuan** [comment]
Hi Yasu!

I pushed a commit fixing that comment. Merging now!

Best,
Brian

**Pull request merged**
