### PR TITLE
Use muon weights

### PR DESCRIPTION
**Pull request by gfacini**
@YasuyukiOkumura 
Look okay?

### CODE REVIEW

**Comment by YasuyukiOkumura** [comment]
Thanks you Gabriel!!! 

I guess maybe you would like to add the b-tag SF branch as well in the mini tree, no?

**Comment by gfacini** [comment]
I have started adding the b-tagging possibility in...I need to test / debug a bit more

**Comment by YasuyukiOkumura** [comment]
Thanks Gabriel. It's sounds like a plan. 
It's OK to merge these two commits! Could you please merge them?

**Comment by gfacini** [comment]
@YasuyukiOkumura 
B-tagging now works!! True/False in config file (false by default) and operating point desired.
I also added each cut to the cutflow so now we have a full cutflow available from xAOD to 
histograms =)

I did not touch the plotting part after but I did change some histogram names and add a few more histograms so work is needed.

**Pull request merged**
