### PR TITLE
Merge updates to b-tagging names and electron branch names

### PR DESCRIPTION
**Pull request by btuan**

### CODE REVIEW

**Comment by YasuyukiOkumura** [comment]
Dear Brian, 

Thanks. It looks good with me and I will merge it.

One request : Since I would like to maintain the ZJetBalanceMiniTreeAnaBase and 
the super analysis class inherited from it (e.g. ZJetBalanceMiniTree_GenBalanceHistograms)
could you please propagate your change in old ProcessZJetBalanceMiniTree.cxx into it? 

For that please let me merge something from my end first in order to avoid conflict,
and after that please propagation your change into ZJetBalanceMiniTree_GenBalanceHistograms.
I will let you know when it is ready. 

Best regards,
Yasu Okumura

**Comment by btuan** [comment]
@YasuyukiOkumura 

Of course! That makes sense. Let me know when the merge from your end occurs, and I will rebase my branch accordingly.

Best,
Brian

**Comment by YasuyukiOkumura** [comment]
Done! Please start your migration!

**Comment by btuan** [comment]
@YasuyukiOkumura 

All done! Please check the [latest commit](https://github.com/UCATLAS/ZJetBalance/commit/7d3ed31a2ad0408678b0c057ad15b636f6c433ef) to make sure everything fits within your vision of the code! I made sure to double-check everything I implemented, so there shouldn't be any gaping mistake.

Best,
Brian

**Pull request merged**
